SELECT *
FROM device
         LEFT JOIN HARD_DISK_PROPERTIES HDP on DEVICE.DEVICE_ID = HDP.HARD_DISK_ID
         LEFT JOIN DESKTOP_PROPERTIES DP on DEVICE.DEVICE_ID = DP.DESKTOP_ID
         LEFT JOIN LAPTOP_PROPERTIES LP on DEVICE.DEVICE_ID = LP.LAPTOP_ID
         LEFT JOIN MONITOR_PROPERTIES MP on DEVICE.DEVICE_ID = MP.MONITOR_ID
WHERE
        device.serial_number = ?